AL:
  ALI: 1
  QUERY_STRATEGIES: ['maxent', 'sument']
  INIT_TRAIN_SIZE: 250
  VAL_SIZE: 1
  FIXED_TEST_SIZE: 250
  INFERENCE_SIZE: 2500
  WIDE_SELECTION: False
  BATCH_SIZE: 250
  RATIO: [150, 75, 25]
  DIVERSE: True
MODEL:
  BATCH_SIZE_PER_IMAGE: 256
  SCORE_THRESH_TEST: 0.5
  NUM_CLASSES: 4
  USE_DROPOUT: False
  USE_EARLY_STOP: False
  TYPE: './detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml'
  WEIGHTS: 'detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl'
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  MAX_ITER_INIT: 2500
  MAX_ITER: 500
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
DATASETS:
  TRAIN: "waymo_train"
  VAL: "waymo_val"
  FIXED: "waymo_fixed"
  TEST: "waymo_test"
DATASET_NAME: 'waymo'
OUTPUT_DIR: './runs/al_scoring_waymo/'
DATASET_DIR: './datasets/waymo/'
