AL:
  ALI: 1
  # QUERY_STRATEGIES: ['sument', 'maxent', 'avgent', 'sumbvsb', 'maxbvsb', 'avgbvsb', 'dropout'] #run0
  QUERY_STRATEGIES: ['dropout'] #run1
  INIT_TRAIN_SIZE: 250
  VAL_SIZE: 1
  FIXED_TEST_SIZE: 250
  INFERENCE_SIZE: 10000
  WIDE_SELECTION: False
  BATCH_SIZE: 250
  RATIO: [150, 75, 25]
MODEL:
  BATCH_SIZE_PER_IMAGE: 256
  SCORE_THRESH_TEST: 0.5
  NUM_CLASSES: 80
  USE_DROPOUT: False
  USE_EARLY_STOP: False
  TYPE: './detectron2_repo/configs/Cityscapes/mask_rcnn_R_50_FPN.yaml'
  WEIGHTS: 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl'
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  MAX_ITER_INIT: 2500
  MAX_ITER: 500
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
DATASETS:
  TRAIN: "naplab_train"
  VAL: "naplab_val"
  FIXED: "naplab_fixed"
  TEST: "naplab_test"
DATASET_NAME: 'naplab'
OUTPUT_DIR: './runs/al_scoring_naplab_new/'
DATASET_DIR: './datasets/naplab/'
