AL:
  ALI: 50
  QUERY_STRATEGIES: ['sumbvsb', 'maxbvsb', 'sument', 'maxent', 'rand']
  INIT_TRAIN_SIZE: 2000
  VAL_SIZE: 1
  FIXED_TEST_SIZE: 3000
  INFERENCE_SIZE: 5000
  WIDE_SELECTION: True
  BATCH_SIZE: 250
  RATIO: [150, 75, 25]
MODEL:
  BATCH_SIZE_PER_IMAGE: 256
  SCORE_THRESH_TEST: 0.5
  NUM_CLASSES: 4
  USE_DROPOUT: False
  USE_EARLY_STOP: False
  TYPE: './detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml'
  WEIGHTS: 'detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl'
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  MAX_ITER_INIT: 2500
  MAX_ITER: 500
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
DATASETS:
  TRAIN: "project_waymo_train"
  VAL: "project_waymo_val"
  FIXED: "project_waymo_fixed"
  TEST: "project_waymo_test"
DATASET_NAME: 'project_waymo'
OUTPUT_DIR: './runs/faster_rcnn_project_waymo/'
DATASET_DIR: './datasets/project_waymo/'
